{
 "title": "环境/总览",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "资源量统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU总量",
   "type": "singlestat",
   "description": "CPU总数",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores)"
    }
   ]
  },
  {
   "title": "CPU Requests占用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) / sum(node:node_num_cpu:sum) * 100"
    }
   ]
  },
  {
   "title": "CPU Limits占用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores) / sum(node:node_num_cpu:sum) * 100"
    }
   ]
  },
  {
   "title": "内存总量",
   "type": "singlestat",
   "description": "内存总量",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "format": "decgbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes)/1024/1024/1024"
    }
   ]
  },
  {
   "title": "Memory Requests占用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) / sum(:node_memory_MemTotal_bytes:sum) * 100"
    }
   ]
  },
  {
   "title": "Memory Limits占用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes) / sum(:node_memory_MemTotal_bytes:sum) * 100"
    }
   ]
  },
  {
   "title": "可分配CPU总量",
   "type": "singlestat",
   "description": "可分配CPU总量",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "可分配内存总量",
   "type": "singlestat",
   "description": "可分配内存总量",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "format": "decgbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes)/1024/1024/1024"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "description": "CPU 当前使用率",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))) * 100",
     "legendFormat": "CPU 当前使用率"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - sum(:node_memory_MemFreeCachedBuffers_bytes:sum) / sum(:node_memory_MemTotal_bytes:sum)) * 100",
     "legendFormat": "内存当前使用率"
    }
   ]
  },
  {
   "title": "节点Ready/Not Ready状态列表",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sort(kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "资源对象统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Deployment期望Pod",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas)",
     "legendFormat": "Deployment期望Pod总数量"
    }
   ]
  },
  {
   "title": "Deployment实际可用Pod",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available)",
     "legendFormat": "Deployment实际可用Pod总数量"
    }
   ]
  },
  {
   "title": "Deployment不可用Pod",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable)",
     "legendFormat": "Deployment不可用Pod总数量"
    }
   ]
  },
  {
   "title": "Daemonset期望Pod",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_desired_number_scheduled)"
    }
   ]
  },
  {
   "title": "Daemonset可用Pod",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_number_available)"
    }
   ]
  },
  {
   "title": "Daemonset不可用Pod",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_number_unavailable)"
    }
   ]
  },
  {
   "title": "Top10 Pod CPU使用排名",
   "type": "graph",
   "description": "Top10 Pod CPU使用排名",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(topk(10, sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\"}[5m])) by (pod_name, container_name))) * 100",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Top10 Pod MEM使用排名",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(container_memory_usage_bytes{image!=\"\"}and{pod_name!=\"\"}) by (pod_name))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "运行过的Pod",
   "type": "singlestat",
   "description": "平台自运行已来的承载过的POD总量",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(kube_pod_status_phase)" }
   ]
  },
  {
   "title": "Phese pre pod",
   "type": "graph",
   "description": "Pod Phese包含如下几个：\n​1. Pending。这个状态意味着，Pod的YAML已经提交给了Kubernetes，API对象已经被创建并保存在Etcd中。但是，这个Pod里有些容器因为某种原因而不能被顺利创建。比如，调度不成功。\n2. Running。这个状态下，Pod已经调度成功，跟一个具体的节点绑定。它包含的容器都已经创建成功，并且至少有一个正在运行中。\n3. Succeeded。这个状态以为着，Pod里的所有容器都正常运行完毕，并且已经退出了。这种情况在运行一次性任务时最为常见。\n4. Failed。这个状态下，Pod里至少有一个容器以不正常的状态（非0的返回码）退出。这个状态的出现，意味着你得想办法Debug这个容器的应用，比如查看Pod的Events和日志。\n5. Unknown。这是一个异常状态，意味着Pod的状态不能持续地被kubelet汇报给kube-apiserver，这很有可能是主从节点（Master和Kubelet）间的通信出现了问题。​​​​",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{}) by (phase)",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "kubelet_running_pod_count{kubernetes_io_role =~ \".*node.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "15分钟内重启过的POD列表",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 29 },
   "targets": [
    {
     "expr": "sum by (pod)(delta(kube_pod_container_status_restarts_total[15m]) > 0)"
    }
   ]
  },
  {
   "title": "运行中Pod",
   "type": "singlestat",
   "description": "pod 运行总数",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=~\"Running\"}==1)"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "singlestat",
   "description": "Ready状态的Pod意味着Pod不仅已经正常启动（Running阶段），而且已经可以对外提供服务了。Running和Readiy是有区别的。",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=~\"true\"})"
    }
   ]
  },
  {
   "title": "重启过的Pod（15m）",
   "type": "singlestat",
   "description": "运行中重启过的pod数 15分钟内",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum by (pod)(delta(kube_pod_container_status_restarts_total[15m]) > 0))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "运行中容器数量",
   "type": "singlestat",
   "description": "运行中容器数量",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 37 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready)"
    }
   ]
  },
  {
   "title": "Container 运行列表",
   "type": "table",
   "description": "Container Status列表",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 37 },
   "targets": [
    {
     "expr": "kube_pod_container_status_running",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "已停止容器数量",
   "type": "singlestat",
   "description": "已停止容器数量",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 42 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated)"
    }
   ]
  },
  { "title": "节点趋势", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "入口链接数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections_total{state=\"active\"}[2m]))",
     "legendFormat": "2分钟内平均active连接"
    },
    {
     "expr": "sum(max_over_time(nginx_ingress_controller_nginx_process_connections[2m]))",
     "legendFormat": "2分钟内最大连接"
    }
   ]
  },
  {
   "title": "入口请求总QPS",
   "type": "singlestat",
   "description": "ingress 的请求 QPS   每秒查询率QPS是对一个特定的查询服务器在规定时间内所处理流量多少的衡量标准",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_nginx_process_requests_total[2m])), 0.001)"
    }
   ]
  },
  {
   "title": "入口网络I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (irate (nginx_ingress_controller_request_size_sum[2m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (irate (nginx_ingress_controller_response_size_sum[2m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "每节点CPU负载（load1）",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_saturation_load1:",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "每节点运行中Pod数量",
   "type": "graph",
   "description": "每节点运行中Pod数量",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kubelet_running_pod_count", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "每节点运行中容器数量",
   "type": "graph",
   "description": "每节点运行中容器数量",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet_running_container_count",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "每节点内存使用率",
   "type": "graph",
   "description": "每节点内存使用率",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "node:node_memory_utilisation:", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "每节点CPU使用率",
   "type": "graph",
   "description": "每节点CPU使用率",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node:node_cpu_utilisation:avg1m) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "节点已用内存",
   "type": "graph",
   "description": "节点已用内存",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_bytes_total:sum - node:node_memory_bytes_available:sum",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "每节点文件系统使用率",
   "type": "graph",
   "description": "每节点文件系统使用率",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_filesystem_usage:\n* on (namespace, pod) group_left (node) node_namespace_pod:kube_pod_info:",
     "legendFormat": "{{node}} , {{device}}"
    }
   ]
  },
  {
   "title": "每节点内存吞吐量",
   "type": "graph",
   "description": "每节点内存吞吐量（swap i/o）",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_swap_io_bytes:sum_rate",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "节点可用剩余内存",
   "type": "graph",
   "description": "节点可用剩余内存",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 67 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_bytes_available:sum",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "每节点磁盘I/O Utilisation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node:node_disk_utilisation:avg_irate) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "每节点磁盘I/O Saturation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_saturation:avg_irate",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "节点网络进带宽（in）",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[5m])*8",
     "legendFormat": "{{instance}} {{device}}_进带宽(in)"
    }
   ]
  },
  {
   "title": "网络出带宽（out）",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total[5m])*8",
     "legendFormat": "{{instance}}    {{device}}_出带宽(out)"
    }
   ]
  },
  {
   "title": "TCP 连接情况",
   "type": "graph",
   "description": "CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nActiveOpens - 已从 CLOSED 状态直接转换到 SYN-SENT 状态的 TCP 平均连接数(1分钟内)\n\nPassiveOpens - 已从 LISTEN 状态直接转换到 SYN-RCVD 状态的 TCP 平均连接数(1分钟内)\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_inuse - 正在使用（正在侦听）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_netstat_Tcp_CurrEstab", "legendFormat": "{{instance}}  ESTABLISHED" },
    { "expr": "node_sockstat_TCP_tw", "legendFormat": "{{instance}}  TCP_tw" },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens[1m])",
     "legendFormat": "{{instance}}   ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens[1m])",
     "legendFormat": "{{instance}}  PassiveOpens"
    },
    { "expr": "node_sockstat_TCP_alloc", "legendFormat": "{{instance}} TCP_alloc" },
    { "expr": "node_sockstat_TCP_inuse", "legendFormat": "{{instance}} TCP_inuse" }
   ]
  },
  {
   "title": "网络每秒异常数（drop）",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_drop_total[5m])",
     "legendFormat": "{{instance}}  {{device}}_异常数(drop)"
    }
   ]
  }
 ]
}