
apiVersion: v1
kind: Service
metadata:
  name: prometheus-webhook-dingtalk-svc
  labels:
    app: prometheus
    component: prometheus-webhook-dingtalk
spec:
  ports:
  - name: http
    port: 8060
    targetPort: http
  selector:
    app: prometheus
    component: prometheus-webhook-dingtalk

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-webhook-dingtalk
  labels:
    app: prometheus
    component: prometheus-webhook-dingtalk
spec:
  selector:
    matchLabels:
      app: prometheus
      component: prometheus-webhook-dingtalk
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
        component: prometheus-webhook-dingtalk
    spec:
      containers:
      - name: prometheus-webhook-dingtalk
        image: quay.io/timonwong/prometheus-webhook-dingtalk:v0.3.0
        ports:
        - name: http
          containerPort: 8060
        args:
        - --ding.profile=webhook1=https://oapi.dingtalk.com/robot/send?access_token=35eb7e694d4bc0e97f3d806448833c3254ef3f899bf9ed966eb21982b6852f5b

